### ISSUE TITLE
Make "send (determination) notice" a required field in OTF Hypha instance

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2460] opened 2021-07-22 12:40 UTC
## Description
On the create determination page for a project (example URL: https://apply.opentech.fund/apply/submissions/XXXX/determination/add/) the primary action button is labelled as Send/Save, as shown in the screenshot below:
 
![image](https://user-images.githubusercontent.com/1899506/126639797-18d6fa6d-12e7-4c15-8688-b48a42c6406d.png)

This is controlled by adding a "Send notice" field to the determinaton forms. If the user who creates the determination form forgets to add this field, it won't be shown.

## Current design
The "Send notice" field is in the "Fields" group, as can be seen below:

![image](https://user-images.githubusercontent.com/1899506/127636775-88ed1edc-b63b-418d-9c0c-5b45f4b9ec07.png)

### Wagtail admin section
In the OTF Hypha instance, make the "Send notice" field a "Required" field (i.e move it from the Fields group to the Required group), so that it is shown on the form by default.

### Determination form
In the OTF Hypha instance, move the checkbox to where it is shown below - 

![Screenshot 2021-07-30 at 12 10 04](https://user-images.githubusercontent.com/1899506/127638463-9f7ecdd9-8194-429b-9135-4112e4504b7d.png)

**Comment by frjo** [comment] 2021-07-23 07:56
You can add a special field to determination that allows you to not send the determination via e-mail. With that in place the Send/Save makes more sense.

**Comment by fourthletter** [comment] 2021-07-25 07:43
1) The 'send message to applicant' button in the email form is not the default. Users would need to know the intention of this checkbox, and remember to check it every time they send a determination.

2) Form creators **need** to manually add the "send message to applicant" to forms. 

Image 1 - send message to applicant
<img width="361" alt="Screen Shot 2021-07-25 at 9 44 35 AM" src="https://user-images.githubusercontent.com/20019656/126891686-fca6130b-00b1-4aef-9c16-e691aef1d20c.png">

Url to test version: https://test-apply.hypha.app/admin/determinations/determinationform/edit/14/

Image 2 - wagtail determination form
<img width="1107" alt="Screen Shot 2021-07-25 at 9 41 45 AM" src="https://user-images.githubusercontent.com/20019656/126891628-a78b3af4-8376-4c1f-8d5d-8854427992e7.png">


Image 3 - email message to applicant

<img width="1246" alt="Screen Shot 2021-07-25 at 9 49 06 AM" src="https://user-images.githubusercontent.com/20019656/126891807-00ab427b-b3af-445e-a2fe-d3de6445c862.png">

**Comment by fourthletter** [comment] 2021-08-17 08:11
Could we please close this? Thank you.

**Comment by fourthletter** [comment] 2021-10-03 20:32
related to #2275 and https://github.com/HyphaApp/hypha/issues/2817

**Comment by frjo** [comment] 2022-09-26 13:14
This is on test now. But do we really want this field to be required?

**Comment by fourthletter** [comment] 2022-09-26 13:48
@frjo the "send message to applicant" field should be on the form and checked by default, doesn't necessarily have to be "required" field.

**Comment by frjo** [comment] 2022-09-26 13:50
Required as in, must be added to the determination form.

**Comment by fourthletter** [comment] 2022-09-26 14:00
![Screenshot 2022-09-26 3 59 51 PM](https://user-images.githubusercontent.com/20019656/192296092-271010fe-e4eb-48a4-8a75-3858ffc630e8.png)

**Comment by fourthletter** [comment] 2022-09-27 09:33
On September 27 standup we discussed 'send notice' should be a default field because this is the expected behavior of determinations

**Closed as completed** 2022-10-04 08:09 UTC
Labels: Type: Enhancement, Status: Tested - approved for live ✅
