### ISSUE TITLE
Add drag and drop widget for upload files wherever it is missing

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3200] opened 2023-02-15 10:51 UTC
### Description

Add drag and drop widget for upload files wherever it is missing

![image](https://user-images.githubusercontent.com/20019656/219007044-edb3add1-7e5f-482e-870e-9de4c5ded457.png)

**Comment by frjo** [comment] 2023-02-15 11:23
Duplicate of https://github.com/HyphaApp/hypha/issues/3166.

**Closed as completed by frjo** 2023-02-15 11:23 UTC
Labels: Status: Needs UI/UX review, Type: Feature
