### ISSUE TITLE
"Admin" button appears even if a user does not have wagtail admin rights

### ISSUE THREAD

**Issue by slifty** [HyphaApp/hypha#2724] opened 2022-02-15 20:11 UTC
**Describe the bug**

When logged in as a user who has access to the admin dashboard but without wagtail admin access the "Admin" button appears even though the user is forbidden to view those wagtail admin pages.  The button should only render for users who are allowed to view the admin pages.

**To Reproduce**

1. Create a user with the "Staff" role (not admin)
2. As a superuser, edit the "Staff" group role so that staff does not have the right to access wagtail admin
3. Navigate to `http://hypha.test:9001/dashboard/`
4. The "admin" button is there

**Expected behavior**

The admin button should ONLY render for administrators / superusers

**Priority**

- Medium : this is confusing for non-technical end users and the button is pretty prominent.

**Affected roles**

- Staff
- Reviewers
- Partners

**Screenshots**

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/208884/154141084-58651aaf-c8b5-4689-b22d-9dfaca1dbad9.png">

**Desktop (please complete the following information):**

 - OS: MacOS
 - Browser Firefox
 - Version 97.0

**Additional context**

I have a fix and will open a PR

**Comment by fourthletter** [comment] 2022-02-15 22:45
The "admin" button is access to the WagTail Admin. The staff role has the administrative rights to access the WagTail Admin to update application forms, publish a fund, etc. 

I recommend changing the user interface so it's more straight forward to the user.

**Comment by slifty** [comment] 2022-02-16 02:59
@fourthletter Just want to be sure I am on the same page to figure out if I just have a local misconfiguration that is the root of this issue.

I have a "Staff" user (*NOT* a superadmin, just "Staff" role with no admin checkbox) -- the original issue's screenshot is taken from a view logged in as that user, and as shown the admin button appears for this non-superuser staff user.

When I click "Admin" I see the following:
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/208884/154187704-975a88ad-4bd5-4a74-8f1b-2de8efa3c1c6.png">

When I manually navigate back to `/dashboard` I see:

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/208884/154187731-7f0a16b2-ea16-44ef-bb5d-888b3ad439e9.png">

It sounds like maybe the bug isn't the rendering of the admin button, but potentially just that something is wrong with my local configuration.  I'll investigate to understand where the "You do not have permission to access the admin" is coming from.

**Comment by slifty** [comment] 2022-02-16 03:10
Update: it appears the issue is that my "Staff" group role did not have "Can access wagtail admin" checked (though worth noting this does not appear to be checked in the test environment either -- e.g. when I run tests, that permission is not applied to users with the "Staff" role.). 

<img width="895" alt="image" src="https://user-images.githubusercontent.com/208884/154188590-5148a7e4-1504-49b0-8395-da49ccec5e38.png">

Checking that box resolves the issue (I will confirm with my team as to whether that box was intentionally unchecked for some reason)

Would it be reasonable to say that Hypha should only render admin button if the user is in a group with the ability to access wagtail admin?

I will update the issue to reflect the updated steps required to reproduce the bug.

Note: I have a patch with this new logic ready; just need to update the tests to account for cases of staff both with AND without wagtail admin rights.

**Comment by frjo** [comment] 2022-02-16 07:58
@slifty Thanks for noticing, and providing a fix for this. With tests as well! That earn you at least one gold star :-).

The root cause is that the original organisation that built Hypha have since day one set the "Can access wagtail admin" for the staff role. I can trace this code back to the first version of Hypha in 2018.

I'm suspect similar issues exist in other places. But there is now one less for certain.

**Closed as completed** 2022-02-19 14:38 UTC
Labels: Type: Bug
