### ISSUE TITLE
When user chooses "Add budget detail" but doesn't complete options, they can still submit.

### ISSUE THREAD

**Issue by bumbleblue** [HyphaApp/hypha#1990] opened 2020-05-07 15:28 UTC
**Describe the bug**

When user chooses "Add budget detail" but doesn't complete Staff, Contractors, Travel , Other, they can still submit.

**Expected behavior**

If "add budget detail" is checked, user needs to complete at least one sub-option.
If sub-options are not completed, show error messages.

**Priority**

- High

**Affected roles**

- Applicants

**Screenshots**

![image](https://user-images.githubusercontent.com/14316263/81313116-b7642600-9087-11ea-9e5f-2586490011dc.png)

**Comment by frjo** [comment] 2020-05-07 15:40
Duplicate of https://github.com/OpenTechFund/hypha/issues/1294

**Comment by ei8fdb** [comment] 2021-04-27 08:45
The "Add budget detail" question is no longer in the Internet Freedom Fund concept note application form so AFAIK this ticket can be closed. (If not, it can be reopened.)

**Closed by ei8fdb** 2021-04-27 08:45 UTC
Labels: Type: Bug
