### ISSUE TITLE
Compliance workflow updates

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3387] opened 2023-05-02 11:56 UTC
As per the feedback from OTF team, here are some feedback for compliance flow. The main change is to enable teams to select assignee for PAF approval as opposed to making it Staff/Lead led.

- [x] 1. Make it optional for the lead to select approvers when submitting the paf for approval. 
- [x] 2. If the lead selects an approver, then that person specifically gets notified as it works today, if no-one is selected then everyone in the group (program, finance, compliance) receives a notification that 'Project documents are ready to be assigned for approval`
- [ ] 3. Approver teams will see the project on their dashboard with status `Needs assignee` till someone has been assigned. once assigned it will only show on the dashboard of the person it is assigned, with the status `Waiting for approval`. 
- [ ] 4. The assignees and change of assignees at any time should be logged in activity feed.
- [ ] 5. Anyone from the teams can assign any specific person from their team to the project approval.
- [ ] 6. Add templates to contractor documents. The staff/admin should be able to add link or upload a file which can be viewed by the applicant.

Prototype:
Workflow for staff: [Link](https://www.figma.com/proto/cmrfUklaIibgEYRFUIifuE/Hypha-designs?page-id=200%3A2&node-id=238-1548&scaling=min-zoom&starting-point-node-id=238%3A1548&show-proto-sidebar=1)
Workflow for approver: [Link](https://www.figma.com/proto/cmrfUklaIibgEYRFUIifuE/Hypha-designs?page-id=200%3A2&node-id=236-841&scaling=min-zoom&starting-point-node-id=236%3A841&show-proto-sidebar=1)
Workflow for contracting: [Link](https://www.figma.com/proto/cmrfUklaIibgEYRFUIifuE/Hypha-designs?page-id=200%3A2&node-id=432-3312&scaling=min-zoom&starting-point-node-id=432%3A3312&show-proto-sidebar=1)
Workflow for applicant: [Link](https://www.figma.com/proto/cmrfUklaIibgEYRFUIifuE/Hypha-designs?page-id=200%3A2&node-id=432-2674&scaling=min-zoom&starting-point-node-id=432%3A2674&show-proto-sidebar=1)

**Comment by abhiXII** [comment] 2023-05-18 10:09
Testing feedback:

- [x] 1. Are we planning to show the alerts twice? or is that just a setting that we can turn off?
<img width="1512" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/3da9610c-724a-4e86-b6c4-87996b6ab79e">

- [x] 2. Can we somehow make it clear that selecting the approvers by staff is optional at this stage. something like this?
<img width="608" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/aa90e647-0c13-4017-8ecd-3bbb0d8ffca1">

Saying `please select...` makes it feel like one has to do it. 
<img width="670" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/428f1064-fd85-456c-92f6-f9a2512e82f1">

- [x] 3. I'm wondering if we should call all of these approvals and not review to make the wording consistent
<img width="662" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/fb08557c-07f4-40ea-9cbe-b67fa8b5dbca">
So maybe we should say Program Approval, Finance Approval etc...

- [x] 4. After submitting should we remove the upload document button?
<img width="1339" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/67564fdd-be66-4d50-9373-086aa4421e7a">

- [x] 5. Let's change this to `Awaiting program team to assign an approver`. Let's also just use sentence case. 
<img width="530" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/55923745-674f-4280-8255-fd7b63f826ee">

- [x] 6. Tiny one - add a space before the bracket - (Nobody... also use lower case n for nobody
<img width="371" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/50f41670-db55-405a-91a2-7cae491781ea">
Change text to this wording and format - `Pending program approval (no assignee)`  and final one: `Pending final approval by CEO (no assignee)` Hope this makes sense. Less text will also keep the height of the box short. 
<img width="507" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/e6e32dc7-07ce-4eb3-b360-1cec1476e497"> 
Also-do we need to mention (no assignee) for final approval? iim guessing that's only one person selected by default? or there's some other cases also.

- [x] 7. On the dashboard for assignee step we need to say `Waiting for assignee`. Also let's make the heading `PAF waiting for assignee` similar to PAF waiting for approval
<img width="764" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/342a974f-db97-44b8-8d54-219892f73148">

- [x] 8. I'd suggest the approve modal to be like this 
<img width="632" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/42031cfa-5e25-4bc8-a3a8-d51b557eb82c">
right now we have this 
<img width="646" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/f3efe7e1-1569-4795-8fb0-f4db95a1d5bf">
so basically adding a grey text, changing the field text to `Select approver` and button to Assign

- [ ] 9. Let's keep the items in this dropdown (and all others also) in alphabetical order?
<img width="660" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/e47fdbe3-0826-4be6-aa3a-4ebc7d599500">

- [ ] 10. Can we please add a line break after `Awaiting approval.` I think most of the times the name will appear broken in two lines-so I'm trying to avoid that. And let's say Pending approval `by`.
<img width="583" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/1d2cfa25-6ad4-4880-9d33-61254d914041">

- [x] 11. For the update PAF status modal, let's use capital for PAF in the title field. Also, do we really need this line : `Project's current status: Waiting for approval` seems inconsistent with other modals also it is not required here.
<img width="659" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/3ed2130c-9197-4454-864d-61729761c3ea">

- [ ] 12. This modal shows up when the lead is trying to update the approver. but I didn't understand the highlighted sentence.
<img width="625" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/55628b71-b3f4-4302-a97f-4bf4ea5f54cc">

- [ ] Wondering how we should tackle `request changes` case for parallel. Right now the VP sees this. Perhaps we should block all action by everyone before the Lead resubmits PAF? So in that everyone will see next steps as `Awaiting project documents to be resubmitted by the lead`. and once resubmitted, everyone can resume from where they last were? ah I see that this is happening but might be a specific bug for VP? because CEO is not seeing any action.  
<img width="1082" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/a6d3d7c4-ce99-4eda-b7df-48412582a36a">
in second case the project was showing on CEO's dashboard while it doesn't show on others' dashboard
<img width="1337" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/e0666e10-3a09-4f0d-a768-4804543bc0e4">
Also thinking that if one group has approved the paf we shouldn't send them further emails about request changes and approval status?
<img width="1332" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/c0a75fd8-78fa-4567-b648-71aeabce7d9e">

**Comment by sandeepsajan0** [comment] 2023-05-18 12:39
>3. I'm wondering if we should call all of these approvals and not review to make the wording consistent

It is the label of PAFReviewerRole, which is configured from wagtail so we can't change that.

>4. After submitting should we remove the upload document button?

This option is for staff and as the staff is trusted members so it was decided to keep it there to provide them the flexibility to upload these anytime(with any status).

>5. Let's change this to Awaiting program team to assign an approver. Let's also just use sentence case.

Again, we are showing here the label from wagtail admin. We can show like ...<label_name> team.... but it wouldn't be wise to update the label itself via code.

> 6. Pending program approval (no assignee)` and final one: `Pending final approval by CEO (no assignee)` Hope this makes sense. .... do we need to mention (no assignee) for final approval? iim guessing that's only one person selected by default? or there's some other cases also.

So, again the first thing is 'Program Approval/Review' is a label configured in wagtail. The second point about the 'final approval', hypha doesn't know about final/last approval because thinks about parallel workflow. Also regarding one user, it might be the case for OTF only(CEO) but for hypha it is a PAFReviewRole(with user groups) just like other approvals so there might be multiple users as well.

>7. On the dashboard for assignee step we need to say Waiting for assignee. 

`Waiting for Approval` is a project status and we don't have `waiting for assignee` as status. Actually, assignee is just a subset of approval status, I don't think we need to have that. Only a good heading might make sense?

>8. I'd suggest the approve modal to be like this

We can update the text but I would say it is good to show wagtail configured label with Select Approver in bold text?

>10. Can we please add a line break after Awaiting approval.

The next step text is just one-liner by design, we use multiple line for instructions(like we show it to applicant for contracting documents). I think we can update the text to make it one line like instead of showing the Awaiting approval and Assigned to ..., we can show direclty Awaiting approval from ....?

>11. For the update PAF status modal, let's use capital for PAF in the title field. Also, do we really need this line : Project's current status: Waiting for approval seems inconsistent with other modals also it is not required here.

I think this line is leftover of the previous workflow, now we can remove it.

>12. This modal shows up when the lead is trying to update the approver. but I didn't understand the highlighted sentence.

I think it was suggested by you 🤔 . It means the first approver who hasn't approved paf yet will get notified for the sequential workflow.

>Wondering how we should tackle request changes case for parallel. Right now the VP sees this. Perhaps we should block all action by everyone before the Lead resubmits PAF? So in that everyone will see next steps as Awaiting project documents to be resubmitted by the lead. and once resubmitted, everyone can resume from where they last were? ah I see that this is happening but might be a specific bug for VP? because CEO is not seeing any action.

As VP is staff + approver. So, VP also has staff permissions until the project is in `Waiting for approval` status. As soon as a project is in Waiting for Approval stage, VP has no permissions more than a PAF Approver. 

>Also thinking that if one group has approved the paf we shouldn't send them further emails about request changes and approval status?

Isn't it already implemented? I think we are sending mail to only approved False approvals' users.

**Closed as completed** 2023-05-30 09:08 UTC
Labels: Type: Enhancement, Status: Needs testing
